global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb_exporter:9216"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
